server:
  port: 9003
  servlet:
    context-path: /thuja
  #nio的web服务配置
  undertow:
    #为工作者创建的I/O线程数
    io-threads: 20
    #工作者线程数量
    worker-threads: 50
    #访问日志
    accesslog:
      enabled: false
spring:
  application:
    name: ansen
  #json对象互转日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      location: /tmp
      #上传文件最大大小:整数字节或MB或G注意字母大写
      max-file-size: 1024MB
      #上传请求最大为
      max-request-size: -1
  profiles:
    active: dev
logging:
  config: classpath:logback.xml
  level:
    com.thuja.mapper: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
mybatis:
  #引用关联资源的类路径资源:classpath*:mapping/*.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.thuja.model
  #开启二级缓存:默认就是开启的
  configuration:
    cache-enabled: true



